### ISSUE TITLE
sign up tidak bisa

### ISSUE THREAD

**Issue by MilenFifi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-portia#1]
sign up dan login jadi nggak bisa soalnya waktu sign in ada fatal error
![Screenshot (6)](https://user-images.githubusercontent.com/55182134/66988936-989f4180-f0ed-11e9-9ab4-d4140d9ee934.png)

**Comment by nashirat** [comment]
Databasenya hilang, harusnya sudah fix
