### ISSUE TITLE
login.php issue

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-portia#10]
![image](https://user-images.githubusercontent.com/49645946/67192821-74f63700-f41e-11e9-97a7-28286c8c9948.png)
kalo aku tekan sign in:
![image](https://user-images.githubusercontent.com/49645946/67192835-7f183580-f41e-11e9-8b69-f295c138941e.png)

**Comment by nashirat** [comment]
Fixed, thanks
