### ISSUE TITLE
register salah email huruf besar, tidak ada warning huruf harusnya kecil, malah page error

### ISSUE THREAD

**Issue by belladewusa** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-portia#2]
![Screenshot (105)](https://user-images.githubusercontent.com/55181780/66990432-5fb49c00-f0f0-11e9-8f19-9b43a76f0745.png)

**Comment by nashirat** [comment]
Itu databasenya hilang, tidak ada masalah dari fungsi login. Mohon errornya dibaca ya : )
