### ISSUE TITLE
Sign Up Lucu

### ISSUE THREAD

**Issue by MilenFifi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-portia#3]
aku mencoba sign  up dengan hanya mengisi username dan password tanpa mengisi email tapi bisa masuk, dan mungkin bisa jalanin waktunya di homepage nya bukan aN aN

**Comment by nashirat** [comment]
Terimakasih, untuk waktu mohon menggunakan browser yang mumpuni, seperti chrome.

**Comment by nashirat** [comment]
Untuk email juga sudah di fix, terimakasih
