### ISSUE TITLE
Error index

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-portia#4]
Pada halaman reg.php terdapat beberapa error mengenai index yaitu username, password dan email.

![Screen Shot 2019-10-17 at 8 12 20 PM](https://user-images.githubusercontent.com/53895082/67011892-9bfcf200-f11a-11e9-9178-a5bcc1aacb3a.png)

**Comment by nashirat** [comment]
Sudah fix, terimakasih
