### ISSUE TITLE
eh coutdown minus men

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-portia#6]
![image](https://user-images.githubusercontent.com/49645946/67173039-ad2e5300-f3e7-11e9-8b31-c40e66dea76b.png)
minus men sawry ngasih issue muehehe

**Comment by nashirat** [comment]
Ini salah dari countdown.jsnya, jadi nanti mungkin akan dihapus saja, tx.

**Comment by nashirat** [comment]
Terimakasih, untuk minus harusnya sudah diperbaiki
![image](https://user-images.githubusercontent.com/55182333/67178820-58e29d80-f3fe-11e9-8007-71b073fd0f03.png)
