### ISSUE TITLE
conn.php issue

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-portia#8]
![image](https://user-images.githubusercontent.com/49645946/67192605-1466fa00-f41e-11e9-8904-667177f4637f.png)
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in F:\Web Development\XAMPP\htdocs\tugas2-web-portia\conn.php:2 Stack trace: #0 {main} thrown in F:\Web Development\XAMPP\htdocs\tugas2-web-portia\conn.php on line 2

**Comment by nashirat** [comment]
fixed, file sampah lupa dihapus, terimakasih
